### ISSUE TITLE
Clarification regarding the overall average grade of a course

### ISSUE THREAD

**Issue by chrisma** [fsr-de/EvaP#1318]
Hi guys,
thanks for your great work on EvaP, it is appreciated!

I was wondering how the `average grade` of a course (i.e. the grade displayed on the overview page) is calculated.
> A short info text / tooltip on the details page of a course on which fields (or which section of fields) are used to calculate the overall average would be helpful to me.

![image](https://user-images.githubusercontent.com/1652117/53795883-349b8480-3f33-11e9-8b00-637e932b719a.png)

I would assume that the overall grade is calculated by averaging all the fields in the `General` section of the evaluation (i.e. `I enjoyed the course...`, etc.). 

![image](https://user-images.githubusercontent.com/1652117/53796417-6a8d3880-3f34-11e9-80a2-124eaa136f65.png)

However, this section can also contain questions whose topics and outcomes instructors may have little control over, e.g. in the `Project` section: `all team members participated equally`.

> Should the amount of questions in the general section (questions that influence the average grade) be reduced, e.g. by placing some questions in a separate section?

![image](https://user-images.githubusercontent.com/1652117/53796836-3c5c2880-3f35-11e9-89f9-7bafe52eafe5.png)

Furthermore, at the very end of the evaluation, there is another section titled `General`, which directly asks for a grade for the course. However, this "total grade" may differ from the average.

>Is the identical naming of sections on purpose?
> Is this total grade as stated by raters also used for calculating the average grade at the top of the evaluation?
> I am unsure which of these two grades is more meaningful. Should the calculated average grade or the direct grade given by students be displayed on the overview? Both?

![image](https://user-images.githubusercontent.com/1652117/53796939-7299a800-3f35-11e9-851b-29dfe59f5efe.png)

Thanks!

**Comment by janno42** [comment]
Hi, thanks for getting in touch with these questions! Let me give an overview here:
- Displaying how much each individual question contributes to the calculated total grade will be dealt with in #1129. This will probably explain most of the non-obvious things mentioned in this issue.
- A description of the grade calculation process can be found in the FAQ. The calculated grade shown above the evaluation includes every of the grades shown below (with varying weights), not only those of the "general" section.
- We might think about individual weights for specific questions in the future, but it doesn't seem very important as individual questions influence the total grade only by a small percentage (usually between 1 and 3 %).
- The two sections "General" have the same name on purpose. We differentiate between "general" questions about the course, exercise, exam, etc. and questions about contributors. You might remember the two questions on the bottom being shown above the contributor questions in the past. This didn't reflect the correct scope (being summarizing questions about everything above and additional things), so they were moved below the contributor questions.
- The last question about the "total grade" shows how the students would rate the course with a single grade. As described in the FAQ, the calculated total grade for the evaluation which is shown on top of the page will be determined by this overall rating question by one third. It is an important question and as such influences the calculated total grade quite a lot. Both grades shouldn't differ too much from each other - if they do, the questionnaire probably missed some important aspects or had a bad focus. Which of both is more meaningful will depend on your expected insights. The overview page shows the calculated total grade because this grade includes every individual answer of the whole evaluation (if only by a very small percentage) and represents an overall (technical) aggregation of all collected answers, whereas the answers to the individual grading question show a more subjective impression.

Please let me know if you have further questions. We are leaving the plain technical view here in some cases, so if the questions turn out to be political decisions rather than implementation-based ones, they should probably be discussed with the evaluation team running the production instance instead. They can then make decisions which can lead to specific requirements which might require changes in the implementation.

**Comment by chrisma** [comment]
Thanks for the fast reply, Johannes!
#1129 looks like a really good idea. :+1: 
The information that the average grade is based on all the collected feedback, weighted by number of answers, is very interesting and helps interpret the presented grade.
Of course, I didn't read the FAQ, where this is described...

Maybe the helpful FAQ could be made more discoverable by including a link to the relevant FAQ entry, i.e. `https://evap.hpi.de/faq#how_are_the_grades_calculated ` (in a tooltip or otherwise)?

![image](https://user-images.githubusercontent.com/1652117/53814888-d4233c00-3f60-11e9-80f5-6b800a9139ad.png)

**Comment by janno42** [comment]
Thanks for the suggestion, I added a note in the weighting info issue.
