### ISSUE TITLE
Option to make text answers public

### ISSUE THREAD

**Issue by marcelgarus** [fsr-de/EvaP#1357]
EvaP is a useful source of information when deciding which courses to choose for the next semester. Grades tell you how good the pace, topics etc of the course are but they don't unveil why they were graded this way. You'd have to listen to anecdotes of others to get a fair impression on the strengths and weaknesses of each course.
After asking around a bit, a number of people would gladly have an option to make a text answer public, so others can see it when the evaluation ended (after the review of the evaluation team, of course). That would provide a more comprehensive overview of each course.

**Comment by janno42** [comment]
This is a discussion we already had many times. However, it's good to talk about it once in a while because opinions can change :)
On short, up to now we thought that if we make text answers available for students, at the same time we have to give lecturers a way to comment back on them for a fair handling. That would lead to a lot more complexity in the whole evaluation process and probably also to political debates about the rising pressure on lecturers that comes with it. For this reason, until now we decided against making text answers publicly available. The foremost use cases of the evaluation are giving feedback to lecturers and having data on which the student representatives and the dean of studies can base talks with lecturers in case of problems. Students deciding which course to take in the next semester is actually subordinated.
I will take the topic into discussions within the evaluation team and the student representatives group and we will talk about the matter in general. As this is a non-technical discussion that will be decided independently from the code development, I will close the issue here for the meantime.
