### ISSUE TITLE
Remove remaining time badge if voted

### ISSUE THREAD

**Issue by janno42** [fsr-de/EvaP#1358]
The "n days left" badge on the student index should be removed if the user already voted for the respective evaluation.

**Comment by pixunil** [comment]
As discussed last monday, from a student's view, I don't see much value in the exact evaluation period. Instead of the full period, I would propose a simple text similar to the badge:

- when the evaluation is in the far future ('starts at mm-dd', 'starts in n days')
- when the evaluation starts immediately ('starts tomorrow', 'starts today'), highlighted in blue
- when the evaluation is open, but not evaluated yet ('n days left', 'ends tomorrow', 'ends today'), highlighted in yellow / red
- when the evaluation is closed, or evaluated (showing only the smiley)

That way, I also propose to move the smiley (whether you evaluated), which bothered me a bit as they don't align…
This is a rather minimal set of information to be displayed, and this proposal is only my view of things.
