### ISSUE TITLE
Make weak reference in signal dispatcher clearer

### ISSUE THREAD

**Issue by felixrindt** [fsr-de/EvaP#1361]
In lines 796 to 808 here: https://github.com/fsr-de/EvaP/blob/b3715158306c27734b29253598c0a644c840b9b0/evap/staff/views.py#L798 (and there's a similar case nearby) we register a receiver inside a view.

To my understanding, every time the view is accessed, a new receiver function is added to the signal. And as we reference the view's request inside the receiver it is captured in the [clojure](https://en.wikipedia.org/wiki/Closure_(computer_programming)) used to store the receiver. That means we keep references and objects in memory until application exit, which is bad right?

**Comment by pixunil** [comment]
The `@receiver` decorator uses its arguments for `Signal.connect` which has a `weak=True`.
That way, the callback is stored only with a weak reference in the signal dispatcher. As the view function does not use the callback, it should get destroyed when the view function finishes its scope.
That's for the theory, so I tried a little good ol' print debugging:

```diff
     @receiver(RewardPointGranting.granted_by_removal)
     def notify_reward_points(grantings, **_kwargs):
+        print('user_edit')
         messages.info(request, …)
```
… prints exactly once when points are granted.

```diff
-    @receiver(RewardPointGranting.granted_by_removal)
+    @receiver(RewardPointGranting.granted_by_removal, weak=False)
     def notify_reward_points(grantings, **_kwargs):
+        print('user_edit')
         messages.info(request, …)
```
… prints multiple times when points are granted, as past instances are kept.

That's only a tiny example, no real proof. The inner function seams to be destroyed as it only has weak references, and according to the [docs](https://docs.python.org/3/library/weakref.html?highlight=garbage+collection) the gc is _free to destroy the object_. As this is a rather simple case, the reference-counting approach would suffice to do this directly after this. Even if the gc does not do it immediately, it can do so later - a memory leak should not be possible.

For testing purposes, these two courses (in the test db) grant points when all participants are removed: [`1545`](http://localhost:8000/staff/semester/21/evaluation/1545/edit) [`1499`](http://localhost:8000/staff/semester/21/evaluation/1499/edit)

**Comment by felixrindt** [comment]
So `notify_reward_points` is a receiver while the response for the POST request is worked on in the view function, which is where the signal is signaled. 
So this actually does what we want, although it's a little unconventional.

**Comment by He3lixxx** [comment]
I'd still like to have some kind of comment there explaining that it will use a weak reference and thus does not cause memory leak, maybe linking to this explanation.

**Comment by pixunil** [comment]
Agreed, it caused enough confusion for one day. If it is sufficient in your opinion, I'd explicitly set `weak=True` to replace a comment or to augment a comment stating, 'This callback will only live for the lifetime of one request' (or similiar).

**Comment by janno42** [comment]
the whole signal thing was used here because we thought it might be nice to separate the rewards app from everything else as much as possible.
some years later i now don't really see a good reason for handling this app differently from everything else. putting `weak` there for some explanation is fine for me and i would also be happy to discuss not using signals at all if that would be a preferred solution.

**Comment by richardebeling** [comment]
Quick update from the future here: This actually doesn't work.

We have no guarantee that the garbage collector runs after the view finishes. We've had [sporadic test failures on CI](https://github.com/e-valuation/EvaP/actions/runs/9067932932/job/24914103337?step:5:71) because the registered receiver in `staff:user_edit` was still notified for a change done in `TestEvaluationEditView` in the edit view...
